### ISSUE TITLE
Y-axis label and legend size

### ISSUE THREAD

**Issue by liamhawkins** [jzhangc/git_R_STATS_KBS#1]
In the Shiny app the y-axis tick label size can be adjusted, however, the label of the y-axis itself cannot be, and the default is quite small. Similar situation with the size of the text in the legend.
![yaxis](https://user-images.githubusercontent.com/22647996/33094440-3559322c-cece-11e7-8c0f-4894bdf98d5e.png)

**Comment by jzhangc** [comment]
These functionalities will be added to the 0.4.3 update.

**Comment by jzhangc** [comment]
0.4.3 is out. The remote version has also been updated.

**Comment by jzhangc** [comment]
0.4.3 is out. The remote version has also been updated.
