### ISSUE TITLE
Error in xvAlign

### ISSUE THREAD

**Issue by birdbio2222** [jzhangc/git_R_STATS_KBS#2]
Hi,

When using rbioplot an error message occurs:
Error in element_text(size = xTickLblSize, family = fontType, angle = xAngle,  : 
  object 'xvAlig**h**' not found

this is strange because in the code it's actually xvAlig**n** 
changing N to H in the code gives the "unused" argument. 

Not sure what's going on any ideas?

**Comment by jzhangc** [comment]
This has been fixed.
